declare @var6 date default 2023-10-16;
declare @var5 double default 3.1415912;
declare @var1 int default 5;
declare @var2 varchar default "simon";
declare @var3 boolean default true;
declare @var4 boolean default False;
declare @var7 null default null;

set @var6 = @var6 + 5;

declare @nombre1 varchar;

set @nombre1 = "cbas+ 1234";
set @nombre1 = @VAR2;

DECLARE @nombre2 varchar, @edad int;

DECLARE @variable_name VARCHAR;

SET @variable_name = @nombre1;

DECLARE @nombre VARCHAR;

DECLARE @edad2 INT DEFAULT 10;

SET @edad = 25;

DECLARE @SI INT;

SET @nombre1 = "\n\"\"aaaa";
